<a href="https://colab.research.google.com/github/corissafuhrman/Linear_Algebra_Coding_Projects/blob/main/Gram_Schmidt_from_Scratch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import matplotlib.pyplot as plt
from sympy import Poly
import sympy as sym
import numpy as np
from numpy import c_

# We'll specify that x and t are variables:
x, t = sym.symbols('x, t')

ll = "loaded"

In [6]:
#Create a vector
r1 = np.matrix([[3], [0], [3], [0]])
r1 = np.array([3, 0, 3, 0])
r1

array([3, 0, 3, 0])

In [8]:
#Vector Arithmetic
r1.dot(r1)

18

In [9]:
#Vector Dot Products
np.sqrt(9)

3.0

In [12]:
#Magnitude of Vector
np.sqrt(r1.dot(r1))

4.242640687119285

#**Gram-Schmidt Orthonormalization Process**

We'll use the Gram-Schmidt Process to find orthogonal vectoris in $R^4$

##Our "Random" Vectors:

In [16]:
r1 = np.array([3, 0, 3, 0])
r2 = np.array([3, 2, 3, 3])
r3 = np.array([-7, -4, -5, -6])
r4 = np.array([-7, -3, -11, 2])

In [17]:
print("r1 = ", r1)

r1 =  [3 0 3 0]


## Process $r_1$

In [22]:
#Choose the vector and subtract off nice orthogonal pieces:
t1 = r1
#t1

#Find the size of t1:
m = np.sqrt(t1.dot(t1))

#Create the nice orthonormal vector u1:
u1 = (1/m) * t1
u1

array([0.70710678, 0.        , 0.70710678, 0.        ])

In [21]:
#Check answer
np.sqrt(2)/2

0.7071067811865476

In [43]:
# Let's check magnitude and orthogonal:
u1.dot(u1)

1.0000000000000002

##Process $r_2$

In [32]:
#Choose the vector and subtract off nice orthogonal pieces:
t2 = r2 - (r2.dot(u1)) * u1
#t2

#Find the size of t2:
m = np.sqrt(t2.dot(t2))
m

#Create the nice orthonormal vector u1:
u2 = (1/m) * t2
u2 

array([-1.23168186e-16,  5.54700196e-01, -1.23168186e-16,  8.32050294e-01])

In [33]:
#Essentially: [0, 0.55, 0, 0.83]
#Should be: [0, 2/sqrt(13), 0, 3/sqrt(13)]
#check:
print(2/np.sqrt(13))
print(3/np.sqrt(13))

0.5547001962252291
0.8320502943378437


In [48]:
print("the size of u2 = ", np.sqrt(u2.dot(u2)))
print("u2 dotted with u1= ", u2.dot(u1))

the size of u2 =  1.0
u2 dotted with u1=  -1.741861189847285e-16


##Process $r_3$

In [41]:
#Choose the vector and subtract off nice orthogonal pieces:
t3 = r3 - (r3.dot(u1)) * u1 - (r3.dot(u2)) * u2


#Find the size of t2:
m = np.sqrt(t3.dot(t3))
m

#Create the nice orthonormal vector u3:
u3 = (1/m) * t3
u3

array([-7.07106781e-01, -3.14018492e-16,  7.07106781e-01, -6.28036983e-16])

In [49]:
print("the size of u3 = ", np.sqrt(u3.dot(u3)))
print("u3 dotted with u1 = ", u3.dot(u1))
print("u3 dotted with u2 = ", u3.dot(u2))

the size of u3 =  0.9999999999999999
u3 dotted with u1 =  0.0
u3 dotted with u2 =  -6.967444759389139e-16


##Process $r_4$

In [42]:
#Choose the vector and subtract off nice orthogonal pieces:
t4 = r4 - (r4.dot(u1)) * u1 - (r4.dot(u2)) * u2 - (r4.dot(u3)) * u3


#Find the size of t2:
m = np.sqrt(t4.dot(t4))
m

#Create the nice orthonormal vector u3:
u4 = (1/m) * t4
u4

array([ 0.        , -0.83205029,  0.        ,  0.5547002 ])

In [50]:
print("the size of u4 = ", np.sqrt(u4.dot(u4)))
print("u4 dotted with u1 = ", u4.dot(u1))
print("u4 dotted with u2 = ", u4.dot(u2))
print("u4 dotted with u3 = ", u4.dot(u3))

the size of u4 =  1.0
u4 dotted with u1 =  0.0
u4 dotted with u2 =  -1.2212453270876722e-15
u4 dotted with u3 =  -8.709305949236341e-17


In [ ]:
print("r1 = ")
print()